### ISSUE TITLE
Python 2 Cleanup tracking issue

### ISSUE THREAD

**Issue by eric-wieser** [cocotb/cocotb#1289]
A list of cleanups and improvements we can make when dropping python 2.

Relates to #767. Maintainers, please add items to this list / edit the list to link PRs.

### Easy changes:

If you're a new contributor, these are a great place to start.

* [x] Adjust (#1337) https://github.com/cocotb/cocotb/blob/9caf77cb6ceae739858ecd4a3760631470aac77c/setup.py#L59
* [x] Change minimum supported version in documentation (gh-1341)
* [x] Remove 2.7 version from Travis CI setup
* [x] Remove reference from `tox.ini`
* [x] Remove function ``isclose`` from ``tests/test_cases/test_cocotb/test_cocotb.py`` (#1489)
* [x] Combine `cocotb_test` and `cocotb_test_35` testbenches (#1489)
* [x] Remove `from __future__ import` line from Python files (but not `Makefile.pylib.*`) (gh-1579)
* [x] Remove `(object)` from `class MyClass(object):` (gh-1579)
* [x] use `type(self)` instead of `self.__class__`. (gh-1579)
* [x] Use `__class__.__qualname__` instead of `__class__.__name__`
* [x] Remove all `__nonzero__` functions which alias `__bool__` (gh-1579)
* [x] Remove 2x "# NOTE: isclose is a Python 3.5+ feature" from ``documentation/source/coroutines.rst`` (gh-1576)
* [x] Update/check installation instructions in documentation and READM
* [x] Remove the conditional compilation here: https://github.com/cocotb/cocotb/blob/ad1e718eab6a107b56c47032f53f282f7d2dbae0/examples/endian_swapper/cosim/io.c#L116. 
* Marginal:
  * [x] make ``u""`` strings normal strings (e.g. in ``documentation/source/conf.py``) (gh-1579)
  * [ ] Move to format string language instead of using old modulus string formatting.

### More involved

* [x] Delete https://github.com/cocotb/cocotb/blob/master/cocotb/share/lib/simulator/simulatormodule_python2.c, and merge https://github.com/cocotb/cocotb/blob/master/cocotb/share/lib/simulator/simulatormodule_python3.c with https://github.com/cocotb/cocotb/blob/master/cocotb/share/lib/simulator/simulatormodule.c (#1342)
* [x] Removes internal uses of `cocotb./_py_compat` (#1434)
* [x] Remove `cocotb.outcome` hacks for python 2 (re `__traceback__`)s (gh-1338)
* [x] Clean up "Before Python 3.3" part in ``documentation/source/coroutines.rst`` (#1341)
* [x] Remove `PY_MAJOR_VERSION < 3` code in `gpi_embed.c`
* [x] Remove or deprecate function ``ReturnValue`` in ``cocotb/cocotb/result.py`` (#1489)
  * [x] Remove usage of function ``ReturnValue`` in our tests and examples
  * [x] Remove internal uses of `ReturnValue` (gh-1440)
* [x] Replace `reject_remaining_kwargs` with direct syntax (#1339)
* [ ] Change coroutines to use `async def`, to teach good practice, in:
  * [ ] ~~tests~~  (filed separately as gh-1731)
  * [x] docs (gh-1576)
  * [ ] ~~examples~~ (filed separately as gh-1730)

### Very involved

* [x] Fix all of the "binary string" interfaces to actually use `bytes`
  * [x] `cocotb.utils.hexdump` (gh-1519)
  * [x] `cocotb.utils.hexdiffs` (gh-1519)
  * [x] `BinaryValue.buff` (gh-1514)
  * [x] `cocotb.generators.byte` ~~(gh-1493)~~  (gh-1514)
  * [x] All of the drivers that produce binary data streams (#1545, gh-1514) (h
* [x] Change all library coroutines to use `async def`, for speed (gh-1523)
* [ ] ~~Add type annotations (for user-facing code)~~ Filed separately as gh-1582

**Comment by cmarqu** [comment]
Not all of those are strictly cleanup:
- Remove ``(object)`` from ``def MyClass(object):``
- Use ``__class__.__qualname__`` instead of ``__class__.__name__``
- Add type annotations (for user-facing code)

**Comment by eric-wieser** [comment]
@cmarqu: Added those to the list, thanks!

**Comment by cmarqu** [comment]
You are too quick, edited in one more line :)

**Comment by cmarqu** [comment]
- Remove 2.7 version from Travis CI setup

**Comment by cmarqu** [comment]
- Change minimum supported version in documentation
- Adjust https://github.com/cocotb/cocotb/blob/9caf77cb6ceae739858ecd4a3760631470aac77c/setup.py#L59

**Comment by cmarqu** [comment]
- Type annotations from docstrings can be removed provided we (a) have them on Python level and (b) we use (the yet unreleased) version of Sphinx 2.4 containing https://github.com/sphinx-doc/sphinx/pull/7018

**Comment by garmin-mjames** [comment]
Remove `PY_MAJOR_VERSION < 3` code in `gpi_embed.c`.

**Comment by ktbarrett** [comment]
Remove reference from `tox.ini`.

**Comment by ktbarrett** [comment]
Remove all `__nonzero__` functions.

**Comment by ktbarrett** [comment]
Fun times ahead. I was rewriting test timeout to use async functions, which required rewriting `with_timeout` to handle async functions, which is most reasonably accomplished as such:

```
async def with_timeout(trigger, timeout_time, timeout_unit=None):

    async def _timeout():
        await cocotb.triggers.Timer(timeout_time, timeout_unit)
        raise cocotb.result.SimTimeoutError()

    return await First(_timeout(), trigger)
```

`First` in this case would `fork` `_timeout()` (or I could here, regardless...). But the timeout exception will only propogate if #922 is resolved first.

**Comment by eric-wieser** [comment]
@ktbarrett, is that something that would be fixed by changing `First` to also be `async def`?

**Comment by ktbarrett** [comment]
@eric-wieser Yes, in fact I already have that change on a branch. I missed it originally.

**Comment by eric-wieser** [comment]
Updated the top-matter to group by difficulty, so new contributors don't pick up a hard task by accident.

**Comment by ktbarrett** [comment]
How should we deal with adding type annotations while still supporting 3.5? Many interesting (to us) types aren't available on all version of 3.5, e.g. `Coroutine`.

**Comment by eric-wieser** [comment]
@ktbarrett: An easy option would be to add a dependency on the `typing` module from pypy, which backports the newer annotations.

Are you sure we need `Coroutine`? My impression was that on `async` functions it was implied.

**Comment by eric-wieser** [comment]
I'd lean towards adding all the easy type annotations first anyway though.

**Comment by ktbarrett** [comment]
@eric-wieser I was documenting the interfaces on #1526 when I ran into this, which is why it has no annotations.

```python
def fork(coro: Union[Coroutine, cocotb.decorators.RunningTask]) -> cocotb.decorators.RunningTask:
    # ...
```

**Comment by eric-wieser** [comment]
@ktbarrett: `collections.abc.Coroutine` was added in 3.5: https://docs.python.org/3/library/collections.abc.html#collections.abc.Coroutine

Sure, maybe you can't use `typing.Coroutine`, but it doesn't really matter.

**Comment by ktbarrett** [comment]
You're right, we aren't ever going to constrain those instances. But I have a feeling this will be an ongoing problem. We saw the same issue other week with `importlib-resources` (they have since added patch versions to the `typing` documentation :^).

**Comment by ktbarrett** [comment]
Move to format string language instead of using old modulus string formatting.

**Comment by ktbarrett** [comment]
I don't know if this is really a Python 2 cleanup issue, but use `type(self)` instead of `self.__class__`.

**Comment by eric-wieser** [comment]
Strictly neither that nor the `.format` calls are python 2 cleanup.

**Comment by ktbarrett** [comment]
Did they renege on the removal of the modulus syntax in Python 3? I thought it was deprecated and "to be removed"?

**Comment by eric-wieser** [comment]
@ktbarrett: Pretty sure they did, especially since `b'{}'.format(1)` is an `AttributeError`, but `b"%d" % 1` isn't.

**Comment by eric-wieser** [comment]
I take it back, `type(x)` _is_ a python 2 cleanup, since it didn't work correctly on old-style classes.

**Comment by eric-wieser** [comment]
Thanks all for assembling this list. I think it's now outlived it's usefulness now that it's mostly complete, so I've extracted remaining tasks to standalone issues.
