### ISSUE TITLE
[Tracking] cocotb 1.8.1

### ISSUE THREAD

**Issue by ktbarrett** [cocotb/cocotb#3369]
Cherry-pick the following PRs.

- [x] #3358 (#3370)
- [x] #3361 (#3370)
- [x] #3367 (#3374)
- [x] https://github.com/cocotb/cocotb/pull/3409 (Python 3.12 wheels)
- [x] Sphinx 7: https://github.com/cocotb/cocotb/pull/3410

Milestone: https://github.com/cocotb/cocotb/milestone/26

Release process checklist:
- [x] Close all issues blocking the milestone
- [x] prepare RC release
- [x] do an extended regression run
- [ ] prepare release announcement blog post
- [x] tag release
- [x] test release build on PyPi
- [ ] send out announcement to blog, Twitter, Linkedin, etc.

**Comment by imphil** [comment]
@cocotb/maintainers Is there anything else we want for 1.8.1 in terms of high-value bug fixes?

I'm wondering if we should do a 1.9 soon as well to include all the other valuable (small-ish) fixes that went into master, I think we only have one breaking fix (the removal of the public decorator) that we cannot have in a 1.x release?

**Comment by rw1nkler** [comment]
May I ask if there is any information available regarding the potential release date of Cocotb 1.8.1?

**Comment by imphil** [comment]
The last batch of cherry-picks: https://github.com/cocotb/cocotb/pull/3429

**Comment by imphil** [comment]
@rw1nkler: It should be available any day now.

**Comment by imphil** [comment]
https://github.com/cocotb/cocotb/releases/tag/v1.8.1 is now out. Enjoy!
