### ISSUE TITLE
[Tracking] cleanup handle.py

### ISSUE THREAD

**Issue by ktbarrett** [cocotb/cocotb#3548]
- [x] ConstantObject does not reveal with the underlying value type is (#2720)
- [x] NonConstantObject type has no purpose (#2720)
- [x] ModifiableObject is both the class for logic arrays and every other value type causing unnecessary functionality to be inherited (#2720)
- [x] NonHierarchyArrayObject is both the class for non-hierarchy arrays and a base class for ModifiableObject and all more specific typed objects causing unnecessary functionality to be inherited (#2720)
- [x] Unclear which types are abstract and which aren't (#2720)
- [x] string casts on handles is the path unless it's a value handle, then it's the string cast of the value (#2720)
- [x] equality is handle equality unless it's a value handle, then it's the equality of the value of the handle and this breaks the hashability, whoops (#2720)
- [x] unnecessary specification of `__ne__` (#2720)
- [x] unnecessary access of handle attributes on handle creation (#2720)
- [ ] unclear what is public method and what isn't
- [x] `__getattr__` syntax conflicts with attribute/method access (introduces `__getitem__` #3655)
- [x] `__iter__` on HierarchyObject and HierarchyArrayObject return child handles instead of keys, like you might expect from a pseudo-dictionary/list type (introduces `_keys`, `_values`, and `_items` #3655)
- [x] `__len__` isn't defined on HierarchyObject (#3655)
- [x] `_id` takes an "extended" argument instead of just having the user add backslashes themselves like they might expect, and extended=True by default (deprecated and replaced with `__getitem__` #3655)
- [x] `_id` is a terrible name (deprecated and replaced with `__getitem__` #3655)
- [x] `_range` isn't available on HierarchyArrayObject (#3655)
- [ ] `_range` is a crappy interface, prefer `left` and `right`
- [ ] `.value` property cannot be properly typed since type systems assume getter and setter of property get and set using the same type
- [x] clean up dead code (#2720)
- [x] clean up unnecessarily inherited attributes/methods (#2720)
- [x] tons of unnecessary logs (#2720)
- [ ] fix/improve documentation
